// <auto-generated />
using GeneticApplication;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeneticApplication.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20241124225757_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GeneticApplication.GenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndividualId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.ToTable("AllGens");
                });

            modelBuilder.Entity("GeneticApplication.IndividualEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PopulationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PopulationId");

                    b.ToTable("AllIndividuals");
                });

            modelBuilder.Entity("GeneticApplication.PopulationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("num1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("num2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("num3")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AllPopulations");
                });

            modelBuilder.Entity("GeneticApplication.GenEntity", b =>
                {
                    b.HasOne("GeneticApplication.IndividualEntity", "Individual")
                        .WithMany("Gens")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("GeneticApplication.IndividualEntity", b =>
                {
                    b.HasOne("GeneticApplication.PopulationEntity", "Population")
                        .WithMany("Individuals")
                        .HasForeignKey("PopulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Population");
                });

            modelBuilder.Entity("GeneticApplication.IndividualEntity", b =>
                {
                    b.Navigation("Gens");
                });

            modelBuilder.Entity("GeneticApplication.PopulationEntity", b =>
                {
                    b.Navigation("Individuals");
                });
#pragma warning restore 612, 618
        }
    }
}
